trace: Add trace-events file for declaring trace events
RH-Author: Jes Sorensen <Jes.Sorensen@redhat.com>
Message-id: <1293468492-25473-2-git-send-email-Jes.Sorensen@redhat.com>
Patchwork-id: 15284
O-Subject: [PATCH 01/20] trace: Add trace-events file for declaring trace events
Bugzilla: 632722
RH-Acked-by: Markus Armbruster <armbru@redhat.com>
RH-Acked-by: Gleb Natapov <gleb@redhat.com>
RH-Acked-by: Marcelo Tosatti <mtosatti@redhat.com>
RH-Acked-by: Daniel P. Berrange <berrange@redhat.com>

From: Stefan Hajnoczi <stefanha@linux.vnet.ibm.com>

This patch introduces the trace-events file where trace events can be
declared like so:

qemu_malloc(size_t size) "size %zu"
qemu_free(void *ptr) "ptr %p"

These trace event declarations are processed by a new tool called
tracetool to generate code for the trace events.  Trace event
declarations are independent of the backend tracing system (LTTng User
Space Tracing, ftrace markers, DTrace).

The default "nop" backend generates empty trace event functions.
Therefore trace events are disabled by default.

The trace-events file serves two purposes:

1. Adding trace events is easy.  It is not necessary to understand the
   details of a backend tracing system.  The trace-events file is a
   single location where trace events can be declared without code
   duplication.

2. QEMU is not tightly coupled to one particular backend tracing system.
   In order to support tracing across QEMU host platforms and to
   anticipate new backend tracing systems that are currently maturing,
   it is important to be flexible and not tied to one system.

This commit includes fixes from Prerna Saxena
<prerna@linux.vnet.ibm.com> and Blue Swirl <blauwirbel@gmail.com>.

Signed-off-by: Stefan Hajnoczi <stefanha@linux.vnet.ibm.com>
(cherry picked from commit 94a420b170b3e997a185a4148accc87bdcd18156)
---
 .gitignore      |    2 +
 Makefile        |   15 ++++-
 Makefile.target |    1 +
 configure       |   19 ++++++
 trace-events    |   24 ++++++++
 tracetool       |  175 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
 6 files changed, 234 insertions(+), 2 deletions(-)
 create mode 100644 trace-events
 create mode 100644 tracetool

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -277,6 +277,7 @@ check_utests="no"
 user_pie="no"
 zero_malloc=""
 spice=""
+trace_backend="nop"
 fake_machine="no"
 
 # OS specific
@@ -475,6 +476,8 @@ for opt do
   --cpu=*)
   ;;
   --target-list=*) target_list="$optarg"
+  ;;
+  --trace-backend=*) trace_backend="$optarg"
   ;;
   --enable-gprof) gprof="yes"
   ;;
@@ -826,6 +829,7 @@ echo "  --with-kvm-trace         enable building the KVM module with the kvm tra
 echo "  --disable-cpu-emulation  disables use of qemu cpu emulation code"
 echo "  --disable-vhost-net      disable vhost-net acceleration support"
 echo "  --enable-vhost-net       enable vhost-net acceleration support"
+echo "  --trace-backend=B        Trace backend nop"
 echo "  --disable-fake-machine   disable -fake-machine option"
 echo "  --enable-fake-machine    enable -fake-machine option"
 echo ""
@@ -2006,6 +2010,18 @@ if compile_prog "" "" ; then
     fdatasync=yes
 fi
 
+##########################################
+# check if trace backend exists
+
+sh "$source_path/tracetool" "--$trace_backend" --check-backend > /dev/null 2> /dev/null
+if test "$?" -ne 0 ; then
+  echo
+  echo "Error: invalid trace backend"
+  echo "Please choose a supported trace backend."
+  echo
+  exit 1
+fi
+
 # End of CC checks
 # After here, no more $cc or $ld runs
 
@@ -2156,6 +2172,7 @@ echo "uuid support      $uuid"
 echo "vhost-net support $vhost_net"
 echo "-fake-machine     $fake_machine"
 echo "Spice             $spice"
+echo "Trace backend     $trace_backend"
 
 if test $sdl_too_old = "yes"; then
 echo "-> Your SDL version is too old - please upgrade to have SDL support"
@@ -2418,6 +2435,8 @@ bsd)
 esac
 
 echo "KVM_KMOD=$kvm_kmod" >> $config_host_mak
+
+echo "TRACE_BACKEND=$trace_backend" >> $config_host_mak
 
 tools=
 if test `expr "$target_list" : ".*softmmu.*"` != 0 ; then
