- Update to 0.13.0 release final - Fixes for vhost - Fix mouse in certain guests (#636887) - Fix issues with WinXP guest install (#579348) - Resolve build issues with S390 (#639471) - Fix Windows XP on Raw Devices (#631591)

diff --git a/ksmtuned.init b/ksmtuned.init
--- a/ksmtuned.init
+++ b/ksmtuned.init
@@ -77,8 +77,14 @@ case "$1" in
 	condrestart
 	;;
   retune)
-        kill -SIGUSR1 `cat ${pidfile}`
+        pid=`cat ${pidfile} 2> /dev/null`
         RETVAL=$?
+        if [ -z "$pid" ]; then
+	    echo $"Cannot retune, service is not running."
+	else
+            kill -SIGUSR1 $pid
+            RETVAL=$?
+	fi
         ;;
   *)
 	echo $"Usage: $prog {start|stop|restart|force-reload|condrestart|try-restart|status|retune|help}"
